#  _     _   _
# | |__ | |_| |_ _ ____  __
# | '_ \| __| __| '_ \ \/ /
# | | | | |_| |_| |_) >  <
# |_| |_|\__|\__| .__/_/\_\ - the clean and concise http testing framework
#               |_|

name: Go - execute library tests

# only trigger on direct push and PRs made to master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# configure job to run unit tests
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: "1.13"
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get module dependencies
      run: go mod download
    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
